# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: event.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65vent.proto\x12\x05types\"\xb7\x01\n\x05\x45vent\x12\x12\n\nevent_type\x18\x01 \x01(\t\x12$\n\x06\x63ustom\x18\x0b \x01(\x0b\x32\x12.types.EventCustomH\x00\x12\x0e\n\x06height\x18[ \x01(\x04\x12\x11\n\treference\x18\\ \x01(\t\x12\x0f\n\x07\x63hainId\x18] \x01(\x04\x12\x14\n\x0c\x62lock_height\x18^ \x01(\x04\x12\x12\n\nblock_hash\x18_ \x01(\x0c\x12\x0f\n\x07\x61\x64\x64ress\x18` \x01(\x0c\x42\x05\n\x03msg\"6\n\x0b\x45ventCustom\x12\x14\n\x0cmsg_type_url\x18\x01 \x01(\t\x12\x11\n\tmsg_bytes\x18\x02 \x01(\x0c\x42.Z,github.com/canopy-network/go-plugin/contractb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/canopy-network/go-plugin/contract'
  _globals['_EVENT']._serialized_start=23
  _globals['_EVENT']._serialized_end=206
  _globals['_EVENTCUSTOM']._serialized_start=208
  _globals['_EVENTCUSTOM']._serialized_end=262
# @@protoc_insertion_point(module_scope)
