name: Dummy Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for the release (e.g. v1.0.0)"
        required: true

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22" # Change this to match your Go version

      - name: Build binaries
        run: |
          make build/wallet
          make build/explorer
          mkdir -p dist

          # AMD64 build
          GOARCH=amd64 CGO_ENABLED=0 GOOS=linux go build -a -o dist/cli-linux-amd64 ./cmd/main/...

          # ARM64 build
          GOARCH=arm64 CGO_ENABLED=0 GOOS=linux go build -a -o dist/cli-linux-arm64 ./cmd/main/...

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: |
            dist/cli-linux-amd64
            dist/cli-linux-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
